on:
  workflow_dispatch:
  pull_request:
    paths:
      - action.yml
      - .github/workflows/ci.yml
jobs:
  ci-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          today: 1
          token: ${{ secrets.GITHUB_TOKEN }}
  ci-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GTD_TODAY: 1
